# Generated by Django 3.0.5 on 2020-07-04 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='blog')),
                ('title', models.CharField(max_length=350)),
                ('tag', models.CharField(max_length=50)),
                ('blog_post', models.TextField()),
            ],
        ),
    ]
