# Generated by Django 3.0.5 on 2020-07-05 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainsite', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='blog')),
                ('title', models.CharField(max_length=350)),
                ('tag', models.CharField(max_length=50)),
                ('couser_description', models.TextField()),
            ],
        ),
    ]
