# Generated by Django 3.0.5 on 2020-07-08 10:05

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('mainsite', '0005_auto_20200707_1118'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='level',
            field=models.CharField(default=datetime.datetime(2020, 7, 8, 10, 5, 38, 82236, tzinfo=utc), max_length=50),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='lessons',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField()),
                ('title', models.CharField(max_length=350)),
                ('postion', models.IntegerField()),
                ('video_url', models.CharField(max_length=550)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainsite.Course')),
            ],
        ),
    ]
