# Generated by Django 3.0.5 on 2020-07-08 10:09

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('mainsite', '0006_auto_20200708_1305'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lessons',
            name='video_url',
        ),
        migrations.AddField(
            model_name='lessons',
            name='video',
            field=models.FileField(default=datetime.datetime(2020, 7, 8, 10, 9, 54, 453369, tzinfo=utc), upload_to='lessons'),
            preserve_default=False,
        ),
    ]
