# Generated by Django 3.0.5 on 2020-07-14 09:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainsite', '0008_coursefeedback'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coursefeedback',
            name='profilepic',
        ),
    ]
