# Generated by Django 3.0.5 on 2020-07-14 09:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainsite', '0009_remove_coursefeedback_profilepic'),
    ]

    operations = [
        migrations.CreateModel(
            name='lessonfeedback',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=350)),
                ('comment', models.TextField()),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainsite.lessons')),
            ],
        ),
    ]
